[bumpver]
current_version = "2021.999.4"
version_pattern = "YYYY.BUILD.UU"
commit_message = "bump version {old_version} -> {new_version}"
commit = true
tag = false
push = false

[bumpver.file_patterns]
"README.md" = [
    "version: {version}",
]
"bumpver.toml" = [
    'current_version = "{version}"',
]
