---
name: Template-Tests

on:
  push:
    branches: [stable]
  pull_request:
    branches: [stable]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.6, 3.7, 3.8]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Step 1: Check out a copy of your repository on the ubuntu-latest machine
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          python-version: ${{ matrix.python }}

      # Step 2
      - name: Install dependencies
        # see https://stackoverflow.com/questions/64589543/cannot-find-pylint-in-git-actions
        uses: actions/setup-python@v2
        run: |
          python -m pip install --upgrade pip
          pip install cookiecutter
          pip install pytest
          pip install pytest-cookies

      # Step 3
      - name: Run pyproject tests
        run: |
          cd pyproject/{{cookiecutter.project_slug}}
          pytest .
          cd ../../

      # Step 4
      - name: Run dsproject tests
        run: |
          cd dsproject/{{cookiecutter.project_slug}}
          pytest .
          cd ../../
