---
name: Template-Tests

on:
  push:
    branches: [stable]
  pull_request:
    branches: [stable]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.6, 3.7, 3.8]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Step 1: Check out a copy of your repository on the ubuntu-latest machine
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Make sure conda is installed, with mamba for speed
      - name: Setup Python with Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python }}
          mamba-version: "*"
          channels: conda-forge,anaconda,defaults
          channel-priority: true
          auto-activate-base: true

      # Step 3
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          make install

      # Step 4
      - name: Run pyproject tests
        run: |
          cd pyproject/{{cookiecutter.project_slug}}
          pytest .
          cd ../../

      # Step 5
      - name: Run dsproject tests
        run: |
          cd dsproject/{{cookiecutter.project_slug}}
          pytest .
          cd ../../
